### PR TITLE
Use kotlinx.html instead of string interpolation

### PR DESCRIPTION
**Pull request by melgenek**
It seems to me that usage of [type-safe builders](https://kotlinlang.org/docs/reference/type-safe-builders.html) is much more convenient way to create type-safe templates than just string interpolation.

This is a sample usage of [kotlinx.html](https://github.com/Kotlin/kotlinx.html) applied to scripting rendering.

### CODE REVIEW

**Comment by melgenek** [comment]
While writing this code I faced an issue.
I wanted to use two ScriptTemplateViewResolvers at the same time with different rendering functions invoked. But I couldn't find the way to set up two ScriptTemplateConfigurers for TemplateViews.
The reason is that the ScriptTemplateConfig is being got inside ScriptTemplateView.autodetectViewConfig. 
Is there a way to use multiple scripting engines at the same time?

**Comment by sdeleuze** [comment]
Sorry for the lag I missed this PR.

Nope, I don't think it is possible easily but you can implement a more clever rendering function that support both.

**Comment by sdeleuze** [comment]
@melgenek Any chance you could rebase this PR against latest `master` in order to allow me to integrate it as an alternative configuration via Spring profiles for example (using different prefix or suffix in order to avoid conflicts between templates)?

**Comment by melgenek** [comment]
@sdeleuze Hello! I've updated the PR. It needed some enhancements because of caching added but it looks pretty neat after all.

By the way, my implementation seems to be XSS safe cause all variables are escaped in tags.

**Comment by jeffcjohnson** [comment]
I love where this is going but dislike Spring's Model<String, Any>.

The example code that binds model["users"] back to a known type seems error prone and tedious to work around the limitations of Spring's Model<String, Any> class.

I would much rather have the controller pass a specific DTO  to the template so the compiler can detect problems.

Is there a way to do that with Spring MVC or would it no longer be Spring MVC at that point?

**Pull request closed without merging**
